website/auth.py
from flask import Blueprint, render_template, request,redirect,url_for,flash
from .forms import LoginForm, RegisterForm
#new imports:
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash,check_password_hash
from .models import User
from . import db

#create a blueprint
bp = Blueprint('auth', __name__ )

@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form submis is fine
    if (register.validate_on_submit() == True):
            #get username, password and email from the form
            uname =register.user_name.data
            pwd = register.password.data
            email=register.email_id.data
            number=register.number.data
            address=register.address.data
            
            #check if a user exists
            u1 = User.query.filter_by(name=uname).first()
            if u1:
                flash('User name already exists, please login')
                return redirect(url_for('auth.login'))
            # don't store the password - create password hash
            pwd_hash = generate_password_hash(pwd)
            #create a new user model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email, number=number, address=address)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')

@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error=None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        u1 = User.query.filter_by(name=user_name).first()
        #if there is no user with that name
        if u1 is None:
            error='Incorrect user name'
        #check the password - notice password hash function
        elif not check_password_hash(u1.password_hash, password): # takes the hash and password
            error='Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(u1)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

website/views.py
from flask import Blueprint, render_template, request, redirect,url_for
from .models import Event 

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    events = Event.query.all()    
    return render_template('index.html', events=events)

@mainbp.route('/search')
def search():
    if request.args['search']:
        print(request.args['search'])
        dest = "%" + request.args['search'] + '%'
        events = Event.query.filter(Event.category.like(dest)).all()
        events += Event.query.filter(Event.status.like(dest)).all()
        return render_template('index.html', events=events)
    else:
        return redirect(url_for('main.index'))

website/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Events App</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>

<body>
   <!-- Header -->
   <header class="bg-light border-bottom">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">

            <!-- Your Travel App Name or Logo -->
            <a href="/" class="navbar-brand">
               Events App
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
               data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
               aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
               <div class="navbar-nav ml-auto">

                  <!-- Register/Login/Logout and welcome -->
                  {% if current_user.is_authenticated %}
                     <a class="nav-item nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                  {% else %}
                     <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                  {% endif %}

                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       Event
                     </a>
                     <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                       <li><a class="dropdown-item" href="{{ url_for('event.create') }}">Create Event</a></li>
                       <li><a class="dropdown-item" href="#update">Update</a></li>
                     </ul>
                   </li>
                  <a class="nav-item nav-link" href="#">Bookings</a>
                  
               </div>
            </div>
         </div>
      </nav>

    {% block header %}
    {% endblock %}

   </header>
      
   {% block content %}
   {% endblock %}
   
    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; IAB207 - 2021</span>
        </div>
    </footer> 
   
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
         integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
         crossorigin="anonymous"></script>
   </body>

</html>

website/templates/index.html
{% extends 'base.html' %}

{% block header %}
      <!--Jumbotron-->
      <div class="container">
         <div class="row justify-content-center mt-5 pb-4">
            <div class="col-md-8">
               <div class="card shadow p-5 mb-5 bg-light">
                  <h1 class="text-center mb-3">Find The Best Category of Events Happening Around You</h1>

                  <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
                     <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
                     <button type="search" class="flex-shrink-1 btn btn-primary my-1">Search</button>
                   </form>
                  
               </div>
            </div>
         </div>
      </div>
{% endblock %}

{% block content %}   
      <div class="container">
         <div class="row mt-5 mb-5 justify-content-center">
            <div class="col-md-10">
               <div class="media border p-3 d-flex justify-content-start">
                  <img class="align-self-center me-3" style="max-width:120px"
                     src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png"
                     alt="Planet Earth">
                  <div class="align-self-center media-body">
                     <h5 class="mt-0">Events around you</h5>
                     <p class="d-none d-sm-block">Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                        scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra
                        turpis. Fusce condimentum nunc ac nisi vulputate fringilla.</p>
                     <a href="{{ url_for('auth.register') }}" class="btn btn-primary">Join Now</a>
                  </div>
               </div>
            </div>
         </div>

         <div class="card-group">
            {% for event in events %}
            <div class="card mx-3">
               <img class="card-img-top"
                  src={{event.image}} alt="event picture">
               <div class="card-body">
                  <h5 class="card-title">{{event.name}}</h5>
                  <p class="card-text">{{event.category}}</p>
                  <p class="card-text">{{event.description}}</p>
                  <p class="card-text">{{event.status}}</p>
               </div>
               <div class="card-footer"><a href = "{{url_for('event.show', id=event.id)}}" class ="btn btn-danger"> View Details </a></div>
            </div>
            {% endfor %}
         </div>
      </div>
{% endblock %}

website/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container-fluid">
<div class="page-header">
    <h4>{{heading}}</h4>
</div>

<!-- flashes any messages to the user -->
{% with messages = get_flashed_messages() %}
{% if messages %} <!-- check if there are any messages -->
  <div class="container-fluid">
    <div class="row mt-3 mb-3">
      <div class="col-md-12">
      {% for message in messages %} <!--loop through the messages-->
        <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}
{% endwith %}

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5">
{{wtf.quick_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4 mb-5 ml-5">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}
</div>
{% endblock %}